
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.url.compiladores.prueba;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 53;
  public static final int ELIMINAR = 28;
  public static final int DEVOLVER = 60;
  public static final int PROTEGIDAS = 21;
  public static final int SI = 58;
  public static final int ENTERO = 3;
  public static final int DIFERENTE = 52;
  public static final int DESDE = 61;
  public static final int ENTONCES = 59;
  public static final int PARENTESISI = 54;
  public static final int PARENTESISF = 55;
  public static final int DECREMENTAR = 11;
  public static final int TAN = 40;
  public static final int INSTANCIAR = 27;
  public static final int PUBLICOS = 67;
  public static final int INCREMENTAR = 10;
  public static final int PRINCIPAL = 32;
  public static final int NUMEROENTERO = 2;
  public static final int IDENTIFICADOR = 12;
  public static final int MAYORQUE = 50;
  public static final int IGUAL = 43;
  public static final int PRIVADAS = 18;
  public static final int SINO = 26;
  public static final int OR = 34;
  public static final int EXTIENDE = 63;
  public static final int MIENTRAS = 62;
  public static final int RAIZ = 42;
  public static final int ESCRIBIR = 56;
  public static final int DESTRUCTOR = 30;
  public static final int INCREMENTO = 15;
  public static final int CADENAABOOL = 37;
  public static final int PROPIEDADES = 64;
  public static final int EOF = 0;
  public static final int ESTATICO = 33;
  public static final int CLASE = 23;
  public static final int DECREMENTO = 16;
  public static final int error = 1;
  public static final int NULO = 6;
  public static final int COMA = 24;
  public static final int PROTEGIDOS = 22;
  public static final int CADENA = 9;
  public static final int MENOS = 45;
  public static final int IDENTIFICADORCLASE = 13;
  public static final int CADENAAENTERO = 35;
  public static final int MENORQUE = 49;
  public static final int REAL = 7;
  public static final int LOG = 41;
  public static final int METODOS = 65;
  public static final int CADENAAREAL = 36;
  public static final int PUNTO = 25;
  public static final int COSENO = 39;
  public static final int PRIVADOS = 19;
  public static final int INCLUIR = 31;
  public static final int SENO = 38;
  public static final int CONSTRUCTOR = 29;
  public static final int FALSO = 5;
  public static final int LEER = 57;
  public static final int PUBLICAS = 66;
  public static final int HACER = 20;
  public static final int BOOLEANO = 8;
  public static final int COMPARACION = 51;
  public static final int VERDADERO = 4;
  public static final int TEXTO = 17;
  public static final int DIVISION = 47;
  public static final int NUMEROREAL = 14;
  public static final int DIVISIONMODULAR = 48;
  public static final int MULTIPLICACION = 46;
  public static final int MAS = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMEROENTERO",
  "ENTERO",
  "VERDADERO",
  "FALSO",
  "NULO",
  "REAL",
  "BOOLEANO",
  "CADENA",
  "INCREMENTAR",
  "DECREMENTAR",
  "IDENTIFICADOR",
  "IDENTIFICADORCLASE",
  "NUMEROREAL",
  "INCREMENTO",
  "DECREMENTO",
  "TEXTO",
  "PRIVADAS",
  "PRIVADOS",
  "HACER",
  "PROTEGIDAS",
  "PROTEGIDOS",
  "CLASE",
  "COMA",
  "PUNTO",
  "SINO",
  "INSTANCIAR",
  "ELIMINAR",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "INCLUIR",
  "PRINCIPAL",
  "ESTATICO",
  "OR",
  "CADENAAENTERO",
  "CADENAAREAL",
  "CADENAABOOL",
  "SENO",
  "COSENO",
  "TAN",
  "LOG",
  "RAIZ",
  "IGUAL",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "DIVISIONMODULAR",
  "MENORQUE",
  "MAYORQUE",
  "COMPARACION",
  "DIFERENTE",
  "DOSPUNTOS",
  "PARENTESISI",
  "PARENTESISF",
  "ESCRIBIR",
  "LEER",
  "SI",
  "ENTONCES",
  "DEVOLVER",
  "DESDE",
  "MIENTRAS",
  "EXTIENDE",
  "PROPIEDADES",
  "METODOS",
  "PUBLICAS",
  "PUBLICOS"
  };
}

