
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.url.analizadorlexico;

/** CUP generated interface containing symbol constants. */
public interface Simbolo {
  /* terminals */
  public static final int COMA = 4;
  public static final int L = 3;
  public static final int error = 1;
  public static final int D = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "D",
  "L",
  "COMA"
  };
}

